[package]
name = "crt"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
strip = true

[dependencies]
image = "0.24.2"
rand = "0.8.5"
clap = { version = "3.1.15", features = ["derive"] }
